/*
 * Author: Raz KaziRo
 * Purpose: Answares for DS - BitsArray.
 * Date: 26.11.2019
 * Language: C
 * Reviewer: Eliya Goldfisher
 */

#include <stdlib.h> /*malloc()*/
#include <string.h> /*strcmp()*/

#include "bits_array.h"

#define RUN_TEST(test, errmsg)\
							{\
								if(test)\
								{\
									printf("SUCCESS\n");\
								}\
								else\
								{\
									printf("\033[1;31m");\
									printf("%s \n", errmsg);\
									printf("\033[0m");\
								}\
							}
#define TEST_ZERO 0
#define TEST_ONE 1
#define TEST_MIDDLE_NUM 4294967295
#define TEST_MAX_NUMBER 18446744073709551615UL
#define TEST_ZERO_STRING "0000000000000000000000000000000000000000000000000000000000000000"
#define TEST_ONE_STRING "0000000000000000000000000000000000000000000000000000000000000001"
#define TEST_MIDDLE_NUM_STRING "0000000000000000000000000000000011111111111111111111111111111111"
#define TEST_MAX_NUM_STRING "1111111111111111111111111111111111111111111111111111111111111111"


#define UNUSED(x) (void)(x)
#define BITS_IN_WORD 64

void TestBArrSetAllBits()
{	
	RUN_TEST(~0ul == BArrSetAllBits(TEST_ZERO), "FAIL: NOT ALL BITS ON (TEST_ZERO)");
	RUN_TEST(~0ul == BArrSetAllBits(TEST_ONE), "FAIL: NOT ALL BITS ON (TEST_ONE)");
	RUN_TEST(~0ul == BArrSetAllBits(TEST_MIDDLE_NUM), "FAIL: NOT ALL BITS ON (TEST_MIDDLE_NUM)");
	RUN_TEST(~0ul == BArrSetAllBits(TEST_MAX_NUMBER), "FAIL: NOT ALL BITS ON (TEST_MAX_NUMBER)");

	RUN_TEST(!(1 == BArrSetAllBits(TEST_ZERO)), "FAIL: ALL BITS ON (TEST_ZERO)");
	RUN_TEST(!(1 == BArrSetAllBits(TEST_ONE)), "FAIL: ALL BITS ON (TEST_ONE)");
	RUN_TEST(!(1 == BArrSetAllBits(TEST_MIDDLE_NUM)), "FAIL: ALL BITS ON (TEST_MIDDLE_NUM)");
	RUN_TEST(!(1 == BArrSetAllBits(TEST_MAX_NUMBER)), "FAIL: ALL BITS ON (TEST_MAX_NUMBER)");
	printf("\n");
}

void TestBArrResetAllBits()
{	
	RUN_TEST(0 == BArrResetAllBits(TEST_ZERO), "FAIL: NOT ALL BITS OFF (TEST_ZERO)");
	RUN_TEST(0 == BArrResetAllBits(TEST_ONE), "FAIL: NOT ALL BITS OFF (TEST_ONE)");
	RUN_TEST(0 == BArrResetAllBits(TEST_MIDDLE_NUM), "FAIL: NOT ALL BITS OFF (TEST_MIDDLE_NUM)");
	RUN_TEST(0 == BArrResetAllBits(TEST_MAX_NUMBER), "FAIL: NOT ALL BITS OFF (TEST_MAX_NUMBER)");

	RUN_TEST(!(1 == BArrResetAllBits(TEST_ZERO)), "FAIL: ALL BITS OFF (TEST_ZERO)");
	RUN_TEST(!(1 == BArrResetAllBits(TEST_ONE)), "FAIL: ALL BITS OFF (TEST_ONE)");
	RUN_TEST(!(1 == BArrResetAllBits(TEST_MIDDLE_NUM)), "FAIL: ALL BITS OFF (TEST_MIDDLE_NUM)");
	RUN_TEST(!(1 == BArrResetAllBits(TEST_MAX_NUMBER)), "FAIL: ALL BITS OFF (TEST_MAX_NUMBER)");
	printf("\n");
}

void TestBArrIsOn()
{	
	RUN_TEST(0 == BArrIsOn(TEST_ZERO,4), "FAIL: BITS IS OFF (TEST_ZERO)");
	RUN_TEST(1 == BArrIsOn(TEST_ONE,1), "FAIL: BITS IS ON (TEST_ONE)");
	RUN_TEST(1 == BArrIsOn(TEST_MIDDLE_NUM,32), "FAIL: BITS IS ON (TEST_MIDDLE_NUM)");
	RUN_TEST(1 == BArrIsOn(TEST_MAX_NUMBER,64), "FAIL: BITS IS ON (TEST_MAX_NUMBER)");

	RUN_TEST(!(1 == BArrIsOn(TEST_ZERO,4)), "FAIL: BIT IS NOT ON (TEST_ZERO)");
	RUN_TEST(!(0 == BArrIsOn(TEST_ONE,1)), "FAIL: BIT IS NOT ON (TEST_ONE)");
	RUN_TEST(!(0 == BArrIsOn(TEST_MIDDLE_NUM,32)), "FAIL: BIT IS NOT ON (TEST_MIDDLE_NUM)");
	RUN_TEST(!(0 == BArrIsOn(TEST_MAX_NUMBER,64)), "FAIL: BIT IS NOT ON (TEST_MAX_NUMBER)");
	printf("\n");

}

void TestBArrIsOff()
{	
	RUN_TEST(1 == BArrIsOff(TEST_ZERO,1), "FAIL: BITS IS OFF (TEST_ZERO)");
	RUN_TEST(1 == BArrIsOff(TEST_ONE,2), "FAIL: BITS IS OFF (TEST_ONE)");
	RUN_TEST(0 == BArrIsOff(TEST_MIDDLE_NUM,32), "FAIL: BITS IS OFF (TEST_MIDDLE_NUM)");
	RUN_TEST(0 == BArrIsOff(TEST_MAX_NUMBER,64), "FAIL: BITS IS OFF (TEST_MAX_NUMBER)");

	RUN_TEST(!(0 == BArrIsOff(TEST_ZERO,4)), "FAIL: BITS IS NOT OFF (TEST_ZERO)");
	RUN_TEST(!(0 == BArrIsOff(TEST_ONE,2)), "FAIL: BITS IS NOT OFF (TEST_ONE)");
	RUN_TEST(!(1 == BArrIsOff(TEST_MIDDLE_NUM,32)), "FAIL: BIT IS NOT OFF (TEST_MIDDLE_NUM)");
	RUN_TEST(!(1 == BArrIsOff(TEST_MAX_NUMBER,64)), "FAIL: BITS IS NOT OFF (TEST_MAX_NUMBER)");
	printf("\n");

}

void TestBArrCountOn()
{	
	RUN_TEST(0 == BArrCountOn(TEST_ZERO), "FAIL:RIGHT COUNT (TEST_ZERO)");
	RUN_TEST(1 == BArrCountOn(TEST_ONE), "FAIL: RIGHT COUNT (TEST_ONE)");
	RUN_TEST(32 == BArrCountOn(TEST_MIDDLE_NUM), "FAIL: RIGHT COUNT (TEST_MIDDLE_NUM)");
	RUN_TEST(64 == BArrCountOn(TEST_MAX_NUMBER), "FAIL: RIGHT COUNT (TEST_MAX_NUMBER)");

	RUN_TEST(!(1 == BArrCountOn(TEST_ZERO)), "FAIL: WRONG COUNT (TEST_ZERO)");
	RUN_TEST(!(4 == BArrCountOn(TEST_ONE)), "FAIL: WRONG COUNT  (TEST_ONE)");
	RUN_TEST(!(8 == BArrCountOn(TEST_MIDDLE_NUM)), "FAIL: WRONG COUNT (TEST_MIDDLE_NUM)");
	RUN_TEST(!(32 == BArrCountOn(TEST_MAX_NUMBER)), "FAIL: WRONG COUNT (TEST_MAX_NUMBER)");
	printf("\n");
}

void TestBArrCountOff()
{
	RUN_TEST(64 == BArrCountOff(TEST_ZERO), "FAIL:RIGHT COUNT OFF (TEST_ZERO)");
	RUN_TEST(63 == BArrCountOff(TEST_ONE), "FAIL: RIGHT COUNT OFF (TEST_ONE)");
	RUN_TEST(32 == BArrCountOff(TEST_MIDDLE_NUM), "FAIL: RIGHT COUNT OFF (TEST_MIDDLE_NUM)");
	RUN_TEST(0 == BArrCountOff(TEST_MAX_NUMBER), "FAIL: RIGHT COUNT OFF (TEST_MAX_NUMBER)");

	RUN_TEST(!(1 == BArrCountOff(TEST_ZERO)), "FAIL: WRONG COUNT OFF (TEST_ZERO)");
	RUN_TEST(!(4 == BArrCountOff(TEST_ONE)), "FAIL: WRONG COUNT OFF  (TEST_ONE)");
	RUN_TEST(!(8 == BArrCountOff(TEST_MIDDLE_NUM)), "FAIL: WRONG COUNT OFF (TEST_MIDDLE_NUM)");
	RUN_TEST(!(32 == BArrCountOff(TEST_MAX_NUMBER)), "FAIL: WRONG COUNT OFF (TEST_MAX_NUMBER)");
	printf("\n");
}

void TestBArrSetBit()
{
	RUN_TEST(1 == BArrSetBit(TEST_ZERO,1,1), "FAIL:RIGHT COUNT OFF (TEST_ZERO)");
	RUN_TEST(0 == BArrSetBit(TEST_ONE,1,0), "FAIL: RIGHT COUNT OFF (TEST_ONE)");
	RUN_TEST(4294967294 == BArrSetBit(TEST_MIDDLE_NUM,1,0), "FAIL: RIGHT COUNT OFF (TEST_MIDDLE_NUM)");
	RUN_TEST(18446744073709551614UL == BArrSetBit(TEST_MAX_NUMBER,1,0), "FAIL: RIGHT COUNT OFF (TEST_MAX_NUMBER)");

	RUN_TEST(!(2 == BArrSetBit(TEST_ZERO,1,1)), "FAIL: WRONG COUNT OFF (TEST_ZERO)");
	RUN_TEST(!(1 == BArrSetBit(TEST_ONE,1,0)), "FAIL: WRONG COUNT OFF  (TEST_ONE)");
	RUN_TEST(!(8 == BArrSetBit(TEST_MIDDLE_NUM,1,0)), "FAIL: WRONG COUNT OFF (TEST_MIDDLE_NUM)");
	RUN_TEST(!(32 == BArrSetBit(TEST_MIDDLE_NUM,1,0)), "FAIL: WRONG COUNT OFF (TEST_MAX_NUMBER)");
	printf("\n");
	
}

void TestBArrSetOn()
{
	RUN_TEST(1 == BArrSetOn(TEST_ZERO,1), "FAIL: RIGHT SET ON (TEST_ZERO)");
	RUN_TEST(3 == BArrSetOn(TEST_ONE,2), "FAIL:RIGHT SET ON (TEST_ONE)");
	RUN_TEST(8589934591 == BArrSetOn(TEST_MIDDLE_NUM,33), "FAIL: RIGHT SET ON (TEST_MIDDLE_NUM)");
	RUN_TEST(18446744073709551615UL == BArrSetOn(TEST_MAX_NUMBER,32), "FAIL:RIGHT SET ON (TEST_MAX_NUMBER)");

	RUN_TEST(!(2 == BArrSetOn(TEST_ZERO,1)), "FAIL: WRONG SET ON (TEST_ZERO)");
	RUN_TEST(!(1 == BArrSetOn(TEST_ONE,2)), "FAIL: WRONG SET ON  (TEST_ONE)");
	RUN_TEST(!(8 == BArrSetOn(TEST_MIDDLE_NUM,33)), "FAIL: WRONG SET ON (TEST_MIDDLE_NUM)");
	RUN_TEST(!(32 == BArrSetOn(TEST_MAX_NUMBER,32)), "FAIL:WRONG SET ON(TEST_MAX_NUMBER)");
	printf("\n");
}

void TestBArrSetOff()
{
	RUN_TEST(0 == BArrSetOff(TEST_ZERO,1), "FAIL:RIGHT COUNT OFF (TEST_ZERO)");
	RUN_TEST(0 == BArrSetOff(TEST_ONE,1), "FAIL: RIGHT COUNT OFF (TEST_ONE)");
	RUN_TEST(4294967294 == BArrSetOff(TEST_MIDDLE_NUM,1), "FAIL: RIGHT COUNT OFF (TEST_MIDDLE_NUM)");
	RUN_TEST(18446744073709551614UL == BArrSetOff(TEST_MAX_NUMBER,1), "FAIL: RIGHT COUNT OFF (TEST_MAX_NUMBER)");

	RUN_TEST(!(2 == BArrSetOff(TEST_ZERO,1)), "FAIL: WRONG COUNT OFF (TEST_ZERO)");
	RUN_TEST(!(9 == BArrSetOff(TEST_ONE,2)), "FAIL: WRONG COUNT OFF (TEST_ONE)");
	RUN_TEST(!(8 == BArrSetOff(TEST_MIDDLE_NUM,32)), "FAIL: WRONG COUNT OFF (TEST_MIDDLE_NUM)");
	RUN_TEST(!(32 == BArrSetOff(TEST_MAX_NUMBER,32)), "FAIL: WRONG COUNT OFF (TEST_MAX_NUMBER)");
	printf("\n");
}

void TestBArrRotateLeft()
{
	RUN_TEST(0 == BArrRotateLeft(TEST_ZERO,64), "FAIL:RIGHT ROTATE LEFT (TEST_ZERO)");
	RUN_TEST(8 == BArrRotateLeft(TEST_ONE,3), "FAIL: RIGHT ROTATE LEFT (TEST_ONE)");
	RUN_TEST(8589934590 == BArrRotateLeft(TEST_MIDDLE_NUM,1), "FAIL: RIGHT ROTATE LEFT (TEST_MIDDLE_NUM)");
	RUN_TEST(18446744073709551615UL == BArrRotateLeft(TEST_MAX_NUMBER,8), "FAIL: RIGHT ROTATE LEFT (TEST_MAX_NUMBER)");

	RUN_TEST(!(45613 == BArrRotateLeft(TEST_ZERO,1)), "FAIL: WRONG ROTATE LEFT (TEST_ZERO)");
	RUN_TEST(!(9545 == BArrRotateLeft(TEST_ONE,2)), "FAIL: WRONG ROTATE LEFT (TEST_ONE)");
	RUN_TEST(!(0 == BArrRotateLeft(TEST_MIDDLE_NUM,32)), "FAIL: WRONG ROTATE LEFT (TEST_MIDDLE_NUM)");
	RUN_TEST(!(32 == BArrRotateLeft(TEST_MAX_NUMBER,32)), "FAIL:WRONG ROTATE LEFT (TEST_MAX_NUMBER)");
	printf("\n");
}

void TestBArrRotateRight()
{
	RUN_TEST(0 == BArrRotateRight(TEST_ZERO,64), "FAIL:RIGHT ROTATE RIGHT (TEST_ZERO)");
	RUN_TEST(2305843009213693952 == BArrRotateRight(TEST_ONE,3), "FAIL: RIGHT ROTATE RIGHT (TEST_ONE)");
	RUN_TEST(9223372039002259455UL == BArrRotateRight(TEST_MIDDLE_NUM,1), "FAIL: RIGHT ROTATE RIGHT (TEST_MIDDLE_NUM)");
	RUN_TEST(18446744073709551615UL == BArrRotateRight(TEST_MAX_NUMBER,8), "FAIL: RIGHT ROTATE RIGHT (TEST_MAX_NUMBER)");

	RUN_TEST(!(896513 == BArrRotateRight(TEST_ZERO,1)), "FAIL: WRONG ROTATE RIGHT (TEST_ZERO)");
	RUN_TEST(!(1454 == BArrRotateRight(TEST_ONE,2)), "FAIL: WRONG ROTATE RIGHT (TEST_ONE)");
	RUN_TEST(!(6548 == BArrRotateRight(TEST_MIDDLE_NUM,32)), "FAIL: WRONG ROTATE RIGHT (TEST_MIDDLE_NUM)");
	RUN_TEST(!(0 == BArrRotateRight(TEST_MAX_NUMBER,32)), "FAIL: WRONG ROTATE RIGHT (TEST_MAX_NUMBER)");
	printf("\n");
}

void TestBArrToString()
{
	char *buffer1 = (char*)malloc(BITS_IN_WORD+1);
	char *buffer2 = (char*)malloc(BITS_IN_WORD+1);
	char *buffer3 = (char*)malloc(BITS_IN_WORD+1);
	char *buffer4 = (char*)malloc(BITS_IN_WORD+1);

	RUN_TEST(0 == strcmp(TEST_ZERO_STRING, BArrToString(TEST_ZERO, buffer1)), "FAIL:RIGHT ZERO STRING (TEST_ZERO)");
	RUN_TEST(0 == strcmp(TEST_ONE_STRING, BArrToString(TEST_ONE, buffer2)), "FAIL:RIGHT ONE STRING (TEST_ONE)");
	RUN_TEST(0 == strcmp(TEST_MIDDLE_NUM_STRING, BArrToString(TEST_MIDDLE_NUM, buffer3)), "FAIL:RIGHT MIDDLE STRING (TEST_MIDDLE)");
	RUN_TEST(0 == strcmp(TEST_MAX_NUM_STRING, BArrToString(TEST_MAX_NUMBER, buffer4)), "FAIL:RIGHT MIDDLE STRING (TEST_MIDDLE)");

	free(buffer1); buffer1 = NULL;
	free(buffer2); buffer2 = NULL;
	free(buffer3); buffer3 = NULL;
	free(buffer4); buffer4 = NULL;

	printf("\n");
}

int main(int argc, char const *argv[])
{
	printf("TestBArrSetAllBits():\n");
	TestBArrSetAllBits();

	printf("TestBArrResetAllBits():\n");
	TestBArrResetAllBits();

	printf("TestBArrIsOn():\n");
	TestBArrIsOn();

	printf("TestBArrIsOff():\n");
	TestBArrIsOff();

	printf("BArrCountOn():\n");
	TestBArrCountOn();

	printf("TestBArrCountOff():\n");
	TestBArrCountOff();

	printf("TestBArrSetBit():\n");
	TestBArrSetBit();

	printf("TestBArrSetOn():\n");
	TestBArrSetOn();

	printf("TestBArrSetOff():\n");
	TestBArrSetOff();

	printf("TestBArrRotateLeft():\n");
	TestBArrRotateLeft();

	printf("TestBArrRotateRight():\n");
	TestBArrRotateRight();

	printf("TestBArrToString():\n");
	TestBArrToString();

	UNUSED(argc);
	UNUSED(argv);

	return 0;
}

